### ISSUE TITLE
Oauth error

### ISSUE THREAD

**Issue by thiagoc7** [froatsnook/meteor-shopify#7]
Hey @froatsnook, thanks for this library!

I can't authenticate, even using your sample app. Get this error:
`Oauth error invalid_request: The redirect_uri is missing or not whitelisted`

Do you know what am I doing wrong?
The `Redirection URL (required)` on shopify partners page should be `http://localhost:3000/`?

Thanks!

**Comment by froatsnook** [comment]
Hey @thiagoc7,

Thanks for creating this issue.  My app in production broke and I hadn't realized it yet!

From https://docs.shopify.com/api/authentication/oauth:

> {redirect_uri} - (Required) substitute this with the URL where you want to redirect the users after they authorize the client. The complete URL specified here must be identical to one of the Application Redirect URLs. Note: in older applications, this parameter was optional, and redirected to the Application Callback URL when no other value was specified.

By default, when you use `Shopify.PublicAppOAuthAuthenticator`, `redirect_uri = Meteor.absoluteUrl("__shopify-auth/" + Meteor.uuid())`.  Then this UUID is used in `AuthRedirect.js` to connect the outgoing request with the incoming response.  But now that the `redirect_uri` has to be whitelisted, the GUID solution isn't possible.  I will try to fix this ASAP.

**Comment by froatsnook** [comment]
My app broke in production for a different reason.  But your bug is real!  New apps require the `redirect_uri` to be whitelisted.  So you should whitelist `localhost:3000/__shopify-auth` (with 2 underscores) in your partner account: App -> Your App -> Edit app settings -> Redirect URL.  I've uploaded version 1.4.1 which uses a URL format that can be whitelisted.  I've also documented this in the README, so please let me know if something isn't clear.

Thanks again for opening this issue.

**Comment by thiagoc7** [comment]
Hi @froatsnook, thanks!
I still have the same issue on the example app, this is the url:

`https://money-project.myshopify.com/admin/oauth/authorize?client_id=435afe29738a57022af98291ff2db7cb&scope=read_content,write_content,read_themes,write_themes,read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_script_tags,write_script_tags,read_fulfillments,write_fulfillments,read_shipping,write_shipping&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F__shopify-auth%2Fd5cb7b55-3c66-4879-80f7-bf9c464d098a`

you can see that the UUID is there. If I remove the last part, `%2Fd5cb7b55-3c66-4879-80f7-bf9c464d098a`, I'm redirected to shopify's page.
But after authorization, when I go back to your app I have `Shopify Auth failed because no handler`.

Cheers!

**Comment by froatsnook** [comment]
1. Just to be sure, you're using the EmbeddedAppSDKTest example, right?
2. What version of froatsnook:shopify is installed?  Check with `meteor list`.  If necessary, run `meteor update`.

I think it must be the case that you're still using 1.3.1 or 1.4.0 since in 1.4.1 then `redirect_uri` looks like `/__shopify-auth?id=UUID`.  Until just now, it was referencing froatsnook:shopify@1.3.1 in the example app's package.js, so update it and give it another try.

**Comment by thiagoc7** [comment]
Yes, I'm using the example app, and just clonned a new repo. Is it working for you?

Thiago Correa
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.1]
On dom, out 11, 2015 at 12:59 PM, froatsnook notifications@github.com wrote:
1. Just to be sure, you're using the EmbeddedAppSDKTest example, right?
2. What version of froatsnook:shopify is installed? Check with meteor list . If necessary, run meteor update .

I think it must be the case that you're still using 1.3.1 since in 1.4.1 then redirect_uri looks like /__shopify-auth?id=UUID . Until just now, it was referencing froatsnook:shopify@1.3.1 in the example
app's package.js, so update it and give it another try.

—
Reply to this email directly or view it on GitHub
[https://github.com/froatsnook/meteor-shopify/issues/7#issuecomment-147213222] .[https://github.com/notifications/beacon/AGXLUGOJz9oE5Ax3mqchPmVN7m4eRW9iks5o6n7agaJpZM4GFnLD.gif]

**Comment by froatsnook** [comment]
What do you mean by _just_?  In the past 9 minutes?  What does `meteor list` say?

**Comment by froatsnook** [comment]
OK I see what's going on.  Let me look into this.

**Comment by froatsnook** [comment]
1.4.2 is published, and hopefully this is fixed.  Thanks for reporting!

**Comment by de-anchorite** [comment]
Hey @froatsnook,

Also wanted to say thanks for the package - it has helped me get most of the way to Shopify authorisation.

However, I have hit this issue with the latest version of your package I'm afraid; the ?id=UUID part of the redirect uri is being URL encoded at the end of the PublicAppOAuthAuthenticator constructor.  This means that the UUID becomes part of the redirect uri that needs to be whitelisted (which isn't possible, due to it being recreated every time).  The UUID should go on the end of the full auth_ui as a "state" parameter.

In the Shopify docs, you will see the state parameter on the uri (also called {nonce}):

https://docs.shopify.com/api/authentication/oauth#asking-for-permission

According to those docs, the state param will be appended to the uri on the callback, so you would need to check for it there to link up the handlers.

I believe I can work around the issue by overriding the created auth_ui, but it seems a shame not to use your automatic auth methods.

Let me know if you would prefer me to try fixing it and submit a pull request.

**Comment by froatsnook** [comment]
Hi @sum1youno. Thanks for your message. Good news! You can just whitelist the url without the uuid (everything up to the '?') and it will work. Give it a try and let me know if it doesn't work. Also, how can I clarify the docs to make this easier? That would be a great pull request!

**Comment by de-anchorite** [comment]
Yeah, tried that with no luck unfortunately.

I have whitelisted http://localhost:3000/__shopify-auth, yet it still doesn't like it.  Incidentally, the Shopify documentation sates the following about the redirect uri:

> {redirect_uri} - (Required) substitute this with the URL where you want to redirect the users after they authorize the client. The complete URL specified here must be identical to one of the Application Redirect URLs. Note: in older applications, this parameter was optional, and redirected to the Application Callback URL when no other value was specified.

which I think suggests that the UUID would need to be included in the whitelist, sue to it being encoded, and Shopify not knowing about the "id" parameter.

I'll let you know how I get on with a workaround, and also if/when I can submit a pull request.

Your documentation is very good btw, more the Shopify OAuth process thats a pain!

**Comment by froatsnook** [comment]
That's strange because I switched it to using query param at the suggestion of a shopify dev, and I'm pretty sure this was working in my tests! I will take another look if I have time this week.

**Comment by dbnoble** [comment]
sum1youno,

Add this to your PublicAppOAuthAuthenticator (just underneath keyset line works fine)

```
redirect_uri: 'http://localhost:3000/__shopify-auth',
```

For some reason, Shopify is requiring you to whitelist it in the app settings AND refer to it directly within the init.

That solved that issue for me, unfortunately I now am getting a different error: 

```
Shopify Auth failed because no handler
```

**Comment by froatsnook** [comment]
@dbnoble I just published 1.4.3 with @sum1youno's pull request.  Hopefully that will fix your `Shopify Auth failed because no handler` error!  Be sure to get rid of the `redirect_uri` you specified so that everything will be automatic (otherwise IIRC meteor-shopify will let you handle it yourself).

**Comment by dbnoble** [comment]
@froatsnook Looks like auth is working properly now with this latest change. Thanks for the support! I was really not looking forward to moving back to rails since I'm pretty rusty in it now.
